
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${SCHEMA}
    username: ${USERNAME}
    password: ${PASSWORD}
    generate-unique-name: false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
